import { Link } from 'react-router-dom'
import MarketingLayout from '../components/MarketingLayout'
import SEO from '../components/SEO'
import { Clock, User } from 'lucide-react'

// Lazy-import: blogPosts.js is generated by the content agent.
import { BLOG_POSTS, BLOG_POST_SLUGS } from '../content/blogPosts'

export default function BlogIndex() {
  // Sort by date desc
  const sorted = [...BLOG_POST_SLUGS].sort(
    (a, b) => new Date(BLOG_POSTS[b].date) - new Date(BLOG_POSTS[a].date)
  )
  const [featured, ...rest] = sorted

  return (
    <MarketingLayout>
      <SEO
        title="Recruitment Ads Blog"
        description="Strategy, science and platform updates for recruiters running paid ads in 2026. Written by recruitment-marketing practitioners, not agencies."
        canonical="https://hireads.app/blog"
        jsonLd={{
          '@context': 'https://schema.org',
          '@type': 'Blog',
          name: 'HireAds Blog',
          description: 'Recruitment advertising strategy, compliance, and platform updates',
        }}
      />

      <section className="max-w-5xl mx-auto px-6 pt-14 pb-8">
        <p className="text-sm text-purple-400 font-semibold mb-3 uppercase tracking-wide">Blog</p>
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Recruitment marketing, decoded.</h1>
        <p className="text-lg text-theme-text2 max-w-2xl">
          Research-backed articles on running ads for hiring — platform updates, compliance, and performance benchmarks you can actually use.
        </p>
      </section>

      {/* Featured */}
      {featured && (
        <section className="max-w-5xl mx-auto px-6 pb-10">
          <PostCard slug={featured} featured />
        </section>
      )}

      {/* Grid */}
      <section className="max-w-5xl mx-auto px-6 pb-20">
        <div className="grid md:grid-cols-2 gap-5">
          {rest.map(slug => <PostCard key={slug} slug={slug} />)}
        </div>
      </section>
    </MarketingLayout>
  )
}

function PostCard({ slug, featured = false }) {
  const p = BLOG_POSTS[slug]
  if (!p) return null
  const date = new Date(p.date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
  return (
    <Link
      to={`/blog/${slug}`}
      className={`block p-6 rounded-2xl bg-theme-card border border-theme-bdr hover:border-purple-500/40 transition-all group ${featured ? 'md:p-8 bg-gradient-to-br from-purple-600/5 to-indigo-600/5' : ''}`}
    >
      <div className="flex flex-wrap gap-2 mb-3">
        {p.tags?.slice(0, 3).map(t => (
          <span key={t} className="text-[10px] uppercase tracking-wide px-2 py-0.5 rounded-full bg-purple-600/15 text-purple-300 border border-purple-500/20">{t}</span>
        ))}
      </div>
      <h2 className={`font-bold mb-2 group-hover:text-purple-400 transition-colors ${featured ? 'text-2xl' : 'text-lg'}`}>{p.title}</h2>
      <p className="text-sm text-theme-text2 mb-4 leading-relaxed">{p.excerpt}</p>
      <div className="flex items-center gap-4 text-xs text-theme-muted">
        <span className="flex items-center gap-1"><User size={11} /> {p.author}</span>
        <span className="flex items-center gap-1"><Clock size={11} /> {p.readingMinutes} min</span>
        <span>{date}</span>
      </div>
    </Link>
  )
}
