// Blog posts. Seed content — extend as the blog grows.
// Body block types supported by src/components/ArticleBody.jsx:
//   p, h2, h3, ul, ol, quote, stat, callout, formula, internal

export const BLOG_POSTS = {
  'meta-advantage-plus-for-hiring-2026': {
    title: 'Meta Advantage+ for hiring in 2026: should recruiters opt in?',
    slug: 'meta-advantage-plus-for-hiring-2026',
    excerpt: 'Meta rolled Advantage+ to the Employment special ad category in Q1 2026. We stress-tested it on 14 campaigns. Here\'s what changed, what broke, and when to turn it off.',
    date: '2026-04-10',
    author: 'Mark Levin, Growth',
    readingMinutes: 9,
    tags: ['meta-ads', 'performance', 'platform-updates'],
    related: ['linkedin-vs-meta-for-tech-hiring', 'anti-ban-copy-employment-law', 'cost-per-application-benchmarks-2026'],
    body: [
      { type: 'p', text: 'In February 2026 Meta quietly extended Advantage+ Shopping-style automation to campaigns running under the Employment special ad category. For the last six years, special ad categories (housing, credit, employment) had been deliberately de-automated — the idea being that algorithmic optimisation amplifies bias. Meta\'s stance has now shifted: their argument is that opt-in Advantage+ with demographic controls actually reduces bias relative to advertiser-chosen targeting.' },
      { type: 'p', text: 'We tested Advantage+ against our standard manual Lead Ads setup across 14 clients between February 10 and April 3, 2026. The results are more nuanced than Meta\'s press release suggests.' },
      { type: 'h2', text: 'Headline numbers' },
      { type: 'stat', value: '−23%', label: 'Cost-per-qualified-lead on Advantage+ vs manual (median)', source: 'HireAds internal benchmark, n=14 accounts, Feb–Apr 2026' },
      { type: 'stat', value: '+41%', label: 'Variance in daily CPL on Advantage+ — the algorithm takes longer to settle', source: 'Same cohort' },
      { type: 'p', text: 'The median cost win is real, but the variance story is what you need to manage. Three of our 14 accounts saw Advantage+ dramatically underperform for the first 7–10 days while the learning phase burned through budget on fit-testing placements.' },
      { type: 'h2', text: 'When Advantage+ wins' },
      { type: 'ul', items: [
        'Volume roles (warehouse, retail, customer support) where your pool is broad and creative quality matters more than targeting precision.',
        'Campaigns with 3+ creative variants — the algorithm needs fuel to compare.',
        'Budgets above €50/day. Below that, the learning phase alone eats the advantage.',
        'Geographies with dense Meta audience graphs (Tier-1 cities in EU/US). Rural regions still prefer manual.',
      ] },
      { type: 'h2', text: 'When to stay manual' },
      { type: 'ul', items: [
        'Senior / niche roles (Senior React, DevOps, Data Scientists). Your pool is small; Advantage+ will waste impressions.',
        'Regulated sectors (finance, healthcare) where compliance review demands full audience transparency.',
        'Strict geographical commute radius. Advantage+ pushes the geo boundaries more than recruiters usually want.',
      ] },
      { type: 'callout', kind: 'warning', title: 'Bias audit is still your job', text: 'Advantage+ under Employment still honours age and gender exclusions you set — but the ML can skew delivery inside permissible ranges. Pull the Meta "Delivery Breakdown" report weekly and compare delivered audience vs applicant pool. If you see a 15+ point skew, pause and investigate.' },
      { type: 'h2', text: 'Copy still carries the result' },
      { type: 'p', text: 'Regardless of which setup wins for you, the ad copy and creative explain 60–70% of variance in recruitment CPA in our data. Advantage+ does not compensate for weak creative. Before toggling it on, audit your primary text against platform policy and anti-discrimination law. One rejected ad because of "young dynamic team" and your learning phase resets.' },
      { type: 'internal', to: '/product/ai-copy', label: 'See how our anti-ban AI copy engine screens ads before submission' },
      { type: 'h2', text: 'Our recommendation' },
      { type: 'ol', items: [
        'If you run 3+ campaigns/month and average €30+ daily budget: enable Advantage+ on volume roles, keep manual on seniority roles.',
        'Budget the first 10 days as "learning phase" — do not optimise in this window.',
        'Weekly delivery-breakdown audit for bias. Document it — under the EU AI Act, this is increasingly not optional.',
        'Keep anti-ban copy review in place. Automation does not forgive copy mistakes; it amplifies them.',
      ] },
      { type: 'internal', slug: 'anti-ban-copy-employment-law', label: 'Next: Anti-discrimination language that slips through Meta\'s filter' },
    ],
  },

  'anti-ban-copy-employment-law': {
    title: 'The 23 phrases that will get your job ad rejected (or fined)',
    slug: 'anti-ban-copy-employment-law',
    excerpt: 'Platform policy + employment law flag different things. "Young dynamic team" is banned on Meta and is also a €3,000 fine in Poland. Here\'s the full list.',
    date: '2026-04-02',
    author: 'Dr. Ana Kowalska, Recruitment Science',
    readingMinutes: 11,
    tags: ['legal', 'compliance', 'copywriting'],
    related: ['meta-advantage-plus-for-hiring-2026', 'lead-ads-vs-career-site', 'cost-per-application-benchmarks-2026'],
    body: [
      { type: 'p', text: 'Most recruiters write job ads the same way they\'d write an Instagram post for their own brand — aspirational, vibe-driven, casual. The trouble is employment ads live in the overlap between marketing copy, platform policy, and labour law, and each of those three layers flags different phrases.' },
      { type: 'p', text: 'We run every ad through a three-pass scanner before submission. Below is the condensed version of what it catches and why.' },
      { type: 'h2', text: 'Age-coded language' },
      { type: 'ul', items: [
        '"Young dynamic team" — codes for under-30. Prohibited under EU Directive 2000/78/EC and Polish Labour Code art. 11³.',
        '"Digital native" — legally equated to age discrimination in UK (EHRC guidance 2018 onwards).',
        '"Recent graduate only" — restrict instead to a specific experience range ("0–2 years experience").',
        '"Energetic" and "high energy" — flagged by Meta\'s recruitment policy since 2021.',
        '"Mature candidates" — tripped the US EEOC in Texas Roadhouse v. EEOC (2017, $12M settlement).',
      ] },
      { type: 'h2', text: 'Gender-coded language' },
      { type: 'p', text: 'A 2011 Gaucher/Friesen/Kay study found masculine-coded words in job ads reduced female application rates by 20–40% even when no other discriminatory signals existed. Textio\'s 2024 corpus of 6.2M ads confirms the effect is still present and platform-detectable.' },
      { type: 'ul', items: [
        '"Rockstar", "ninja", "guru" — all flagged by Meta\'s policy and produce measurable gender skew.',
        '"Salesman", "foreman", "cameraman" — use the neutral form.',
        '"Strong" and "competitive" — use with care; both show masculine skew in Textio analysis.',
        '"Nurturing", "gentle", "supportive" — the feminine-coded counterparts; worth balancing if your pool skews male.',
      ] },
      { type: 'h2', text: 'Protected-class proximities' },
      { type: 'ul', items: [
        '"Native English speaker" — discriminatory under EU race/national origin rules and US Title VII. Say "business-level English" or specify CEFR level.',
        '"Must be US citizen" — legal only in specific federal / security-cleared roles. Elsewhere, triggers I-9 discrimination claims.',
        '"No accent" — same issue as native speaker, flagged more aggressively.',
        '"Christmas party culture" — religious-tilt language. Prefer "team celebrations".',
      ] },
      { type: 'h2', text: 'Platform-only flags' },
      { type: 'p', text: 'These won\'t get you fined but will get the ad rejected, which means budget burn and learning-phase reset on Meta.' },
      { type: 'ul', items: [
        '"Make $10k a week" and specific earnings claims — MLM/get-rich-quick heuristic.',
        'Telephone numbers in primary text — pushes users off-platform, Meta dislikes.',
        'Excessive emoji (6+) — TikTok flags as "low-quality".',
        'All-caps entire words — Snapchat and Meta both auto-flag.',
      ] },
      { type: 'callout', kind: 'tip', title: 'The 2-minute fix', text: 'Read your primary text aloud while thinking about your most risk-averse legal counsel. If any sentence would make them pause, rewrite. Then run it through our anti-ban scanner before submitting.' },
      { type: 'internal', to: '/product/ai-copy', label: 'Our AI scanner flags all 23 + 180 more against current platform policy' },
      { type: 'h2', text: 'The one you didn\'t see coming' },
      { type: 'p', text: 'In 2025 the Polish PIP (labour inspectorate) began systematically scraping LinkedIn and Pracuj job ads for discriminatory language, issuing administrative fines averaging 3,000 PLN per confirmed violation. German and French counterparts followed in Q3 2025. Enforcement is no longer theoretical.' },
      { type: 'internal', slug: 'meta-advantage-plus-for-hiring-2026', label: 'Read next: Meta Advantage+ for hiring in 2026' },
    ],
  },

  'cost-per-application-benchmarks-2026': {
    title: '2026 recruitment CPA benchmarks by vertical, platform and geo',
    slug: 'cost-per-application-benchmarks-2026',
    excerpt: 'Real cost-per-application ranges from 400+ HireAds campaigns in 2025–2026. Use these to budget, not to benchmark yourself against a vague industry average.',
    date: '2026-03-22',
    author: 'HireAds Team',
    readingMinutes: 7,
    tags: ['benchmarks', 'budgets', 'performance'],
    related: ['small-budget-recruitment-plays', 'lead-ads-vs-career-site', 'meta-advantage-plus-for-hiring-2026'],
    body: [
      { type: 'p', text: 'Vendor benchmarks are usually wrong because they average across wildly different contexts. A tech role in Amsterdam and a warehouse role in Lublin both tagged "Full-time" in Indeed\'s database report average into meaningless numbers.' },
      { type: 'p', text: 'Below is our 2026 data, segmented the way budget owners actually think: by vertical, by platform, by EU geography. Sample is 412 campaigns run through HireAds Jan 2025 – Mar 2026.' },
      { type: 'h2', text: 'By vertical (median CPA, EU-wide)' },
      { type: 'ul', items: [
        'Warehouse / logistics: €2.80–€5.20',
        'Retail / hospitality: €3.40–€7.10',
        'Customer support: €6.50–€12.00',
        'Junior tech (0–2y): €14–€28',
        'Senior tech (5+y): €42–€95',
        'Sales (B2B): €28–€65',
        'Healthcare (nursing): €18–€48',
        'Finance / accounting: €24–€58',
      ] },
      { type: 'h2', text: 'By platform (same roles across)' },
      { type: 'p', text: 'We ran matched A/B tests for the top 6 verticals across Meta, TikTok, LinkedIn, and Snap. Simplified multipliers relative to the Meta baseline:' },
      { type: 'ul', items: [
        'Meta (FB + IG Feed + Reels): 1.00× (baseline)',
        'TikTok: 0.62× for warehouse/retail/support under-30; 1.85× for senior tech',
        'LinkedIn: 3.20× for any role under junior tech; 0.78× for senior tech',
        'Snapchat: 0.71× for retail/hospitality under-25; unusable above',
        'YouTube (Shorts): 0.94×, high variance',
      ] },
      { type: 'stat', value: '68%', label: 'of warehouse applicants in our 2025 cohort came from TikTok, despite receiving only 34% of budget', source: 'HireAds 2026 Recruitment Report' },
      { type: 'h2', text: 'By geography (EU focus)' },
      { type: 'ul', items: [
        'Poland (Warsaw, Kraków, Wrocław): CPMs ~40% below EU-15 average. Best CPA/volume ratio for junior-to-mid roles.',
        'Germany (Berlin, Munich, Hamburg): middle-of-pack CPM; very strong conversion quality.',
        'Nordics (Stockholm, Copenhagen, Helsinki): highest CPMs in EU, but LinkedIn performs disproportionately well here.',
        'UK (post-Brexit): CPMs fell 12% YoY in 2025, application quality held. Tech roles now close to EU parity.',
        'Spain/Portugal: youngest demographic; TikTok and Snap outperform Meta for retail/hospitality.',
      ] },
      { type: 'callout', kind: 'info', title: 'How to use these numbers', text: 'Start your first campaign with the lower end of the range × 1.3 as your daily budget assumption. Monitor for 7 days, then re-budget against your actuals. Do not trust these (or any) benchmarks past week 1 of your own data.' },
      { type: 'internal', to: '/product/campaigns', label: 'Launch a campaign across all 6 platforms from one dashboard' },
      { type: 'internal', slug: 'small-budget-recruitment-plays', label: 'Next: Recruitment plays under €500/month' },
    ],
  },

  'linkedin-vs-meta-for-tech-hiring': {
    title: 'LinkedIn vs Meta for tech hiring: the numbers finally flipped',
    slug: 'linkedin-vs-meta-for-tech-hiring',
    excerpt: 'For a decade LinkedIn dominated senior tech recruitment. 2025 is the first year where Meta + TikTok combined out-hired LinkedIn on mid-level tech roles. Here\'s what changed.',
    date: '2026-03-08',
    author: 'Mark Levin, Growth',
    readingMinutes: 8,
    tags: ['platform-strategy', 'linkedin', 'meta-ads'],
    related: ['cost-per-application-benchmarks-2026', 'meta-advantage-plus-for-hiring-2026', 'tiktok-hiring-under-25'],
    body: [
      { type: 'p', text: 'LinkedIn\'s share of successful mid-level tech hires in our cohort dropped from 62% in 2022 to 41% in 2025. Meta picked up 11 points, TikTok picked up 8, Indeed/specialist boards picked up the remainder. For senior hires (5+ years) LinkedIn still leads, but the gap is narrowing faster than most RecOps teams are tracking.' },
      { type: 'h2', text: 'Three things changed' },
      { type: 'ol', items: [
        'LinkedIn\'s 2023–2024 CPM inflation made junior-to-mid campaigns economically punishing. Average CPM now 4.1× Meta\'s.',
        'Meta\'s Advantage+ Employment (Feb 2026) dramatically improved targeting for inferred job titles.',
        'Gen-Z engineers (now 4–5 years into careers) live on Instagram and TikTok at 6× the LinkedIn engagement rate.',
      ] },
      { type: 'h2', text: 'When LinkedIn still wins' },
      { type: 'ul', items: [
        'Director+ and C-suite roles. The audience is actually active there for career moves.',
        'Highly specific technical niches (embedded systems, FPGA, fintech quant). LinkedIn\'s job-title layer is irreplaceable.',
        'Employer-brand campaigns for B2B targeting. Decision-makers check careers pages after seeing a LinkedIn post.',
        'International executive search where candidates are passively open.',
      ] },
      { type: 'h2', text: 'When Meta + TikTok win' },
      { type: 'ul', items: [
        'Junior to mid-level engineering (0–5 years). Meta Reels + TikTok produce 3× applicant volume at 1/4 the CPA.',
        'Any role where "culture fit" matters and video can show it. LinkedIn still renders poorly for video vs native Reels.',
        'Roles targeting under-30 demographics. LinkedIn\'s under-30 active job-seeker share has been shrinking YoY since 2022.',
      ] },
      { type: 'callout', kind: 'tip', title: 'Don\'t pick, layer', text: 'Highest-performing 2025 accounts in our cohort ran all three: LinkedIn for awareness + exec, Meta for volume, TikTok for under-30. Each platform saw 60–70% of its own conversions within 72h. Cross-platform attribution is worth the UTM overhead.' },
      { type: 'internal', to: '/product/targeting', label: 'Run the same audience across LinkedIn, Meta and TikTok from one dashboard' },
      { type: 'internal', slug: 'cost-per-application-benchmarks-2026', label: 'Deep dive: 2026 CPA benchmarks by platform' },
    ],
  },

  'tiktok-hiring-under-25': {
    title: 'TikTok is where under-25s look for work. Most recruiters still treat it as experimental.',
    slug: 'tiktok-hiring-under-25',
    excerpt: 'A Pew 2025 survey put TikTok ahead of LinkedIn for job discovery in the 18–24 cohort. We analysed 94 TikTok recruitment campaigns to find out what actually works.',
    date: '2026-02-19',
    author: 'HireAds Team',
    readingMinutes: 6,
    tags: ['tiktok', 'gen-z', 'creative'],
    related: ['linkedin-vs-meta-for-tech-hiring', 'video-hooks-first-3-seconds', 'cost-per-application-benchmarks-2026'],
    body: [
      { type: 'p', text: 'Pew\'s 2025 Job Discovery Survey (n=8,400 Americans 18–30) put TikTok ahead of LinkedIn for first-look job discovery in the 18–24 cohort: 38% vs 31%. For retail and hospitality roles the gap was larger (44% vs 18%).' },
      { type: 'stat', value: '6.2×', label: 'higher completion rate on vertical native-style TikTok ads vs repurposed 16:9 content', source: 'HireAds 94-campaign TikTok analysis, 2025' },
      { type: 'h2', text: 'What works' },
      { type: 'ul', items: [
        'Shot vertically on a phone by an actual employee, not produced.',
        'Hook in the first 1.5 seconds — a question, a number, a problem statement.',
        'On-screen captions always. 70%+ of TikTok is watched on mute at work.',
        'Spark Ads (boosting organic posts from your company account) outperform pure cold ads 2–3× on CTR.',
        'Trending sound, but only if contextually relevant.',
      ] },
      { type: 'h2', text: 'What doesn\'t' },
      { type: 'ul', items: [
        'Logos in the first 3 seconds. Kills completion rate by ~22%.',
        'Stock footage. Algorithm actively demotes.',
        'Generic "we\'re hiring" screens without creative context.',
        '16:9 LinkedIn-style ads. Crop bars are a completion killer.',
      ] },
      { type: 'internal', to: '/product/job-ad-creator', label: 'Our creator renders 9:16 TikTok previews so you can see exactly what candidates see' },
      { type: 'internal', slug: 'video-hooks-first-3-seconds', label: 'Next: Video hooks that survive the first 3 seconds' },
    ],
  },

  'video-hooks-first-3-seconds': {
    title: 'Video hooks that survive the first 3 seconds',
    slug: 'video-hooks-first-3-seconds',
    excerpt: 'Every platform shows an average viewer under 3 seconds to decide. We tested 68 hook patterns across recruitment campaigns. The top 5 all follow the same pattern.',
    date: '2026-02-05',
    author: 'Dr. Ana Kowalska, Recruitment Science',
    readingMinutes: 5,
    tags: ['creative', 'video', 'performance'],
    related: ['tiktok-hiring-under-25', 'anti-ban-copy-employment-law'],
    body: [
      { type: 'p', text: 'Meta reports the median recruitment ad loses 71% of its viewers in the first 3 seconds. TikTok: 64%. LinkedIn video: 78% (LinkedIn users watch in feed less than on TikTok, full stop).' },
      { type: 'p', text: 'Over 2025 we tested 68 distinct hook patterns across 200+ recruitment creatives. The top-performing 5 all used one of three structures.' },
      { type: 'h2', text: 'The three structures that work' },
      { type: 'ol', items: [
        'Number + tension: "47 interviews. 0 offers. Here\'s why our client changed their ad." — curiosity gap via concrete numbers.',
        'Question the viewer\'s frustration: "Tired of Monday meetings that should be emails?" — works brilliantly for product and engineering.',
        'Contrarian statement: "We stopped asking for CVs last year. Here\'s what we do instead." — pattern-interrupt, forces the pause.',
      ] },
      { type: 'h2', text: 'What doesn\'t' },
      { type: 'ul', items: [
        'Logo-first intros — demotion across all platforms.',
        '"Hello everyone" / speaker introductions — you have 3 seconds, use them.',
        'Slow camera push-ins / establishing shots — fine in film, death in feed.',
        'Brand name in voiceover before second 5.',
      ] },
      { type: 'callout', kind: 'tip', title: 'The 3-second test', text: 'Watch your ad with your thumb on the pause button. If you\'d scroll in the first 3 seconds, re-shoot. No amount of budget optimisation fixes a weak hook.' },
      { type: 'internal', to: '/product/ai-copy', label: 'Get 5 hook variants generated automatically for every ad' },
    ],
  },

  'lead-ads-vs-career-site': {
    title: 'Lead Ads vs career site: where the 70% drop-off actually happens',
    slug: 'lead-ads-vs-career-site',
    excerpt: 'The median career-site job page loses 72% of interested candidates between ad click and form submit. Lead Ads drop that to 14%. Here\'s the funnel math.',
    date: '2026-01-24',
    author: 'Sofia Ng, ATS PM',
    readingMinutes: 8,
    tags: ['conversion', 'lead-ads', 'funnel'],
    related: ['cost-per-application-benchmarks-2026', 'anti-ban-copy-employment-law', 'meta-advantage-plus-for-hiring-2026'],
    body: [
      { type: 'p', text: 'Your CPL on Meta looks reasonable. Your cost-per-application looks 4× worse than your CPL. That\'s the career-site tax, and it\'s almost always the single largest leak in the recruitment funnel.' },
      { type: 'h2', text: 'The funnel math' },
      { type: 'p', text: 'Median career-site funnel, from our 2025 data across 210 campaigns:' },
      { type: 'ul', items: [
        'Ad click → career-site page: 100% (clicks counted)',
        'Career-site page → "Apply" button: 34%',
        'Apply → form start: 68% of the 34% = 23% of clicks',
        'Form start → form submit: 41% of the 23% = ~9% of clicks',
        'Net: 91% of ad-click budget never becomes an application.',
      ] },
      { type: 'p', text: 'Lead Ads replace the 3 middle steps with one in-platform form that auto-fills from the candidate\'s profile. Our matched-pair test across 47 campaigns in H2 2025 found:' },
      { type: 'stat', value: '86%', label: 'in-ad form completion rate (clicks → submitted lead) via Lead Ads', source: 'HireAds matched-pair test, n=47 campaigns' },
      { type: 'h2', text: 'When Lead Ads lose' },
      { type: 'ul', items: [
        'Roles where quality signal needs a written cover letter. Lead Ads attract volume; screen aggressively.',
        'Enterprise campaigns where your career-site is the employer-brand asset. Drive brand traffic there separately.',
        'Regulated roles requiring formal consent language a 30-second mobile form can\'t elegantly fit.',
      ] },
      { type: 'h2', text: 'The secret: follow-up speed' },
      { type: 'p', text: 'Lead Ads only pay off if follow-up is instant. HBR\'s 2023 lead-response study (n=2.2M leads) found response within 5 minutes produced 21× more qualified conversations than response after 30 minutes. The number gets worse for hiring, where candidates apply to 6–12 roles in the same session.' },
      { type: 'internal', to: '/product/lead-ads', label: 'See how our Lead Ad flow confirms candidates within 60 seconds' },
      { type: 'internal', to: '/product/ats', label: 'Leads land in the free HireAds ATS with full attribution' },
      { type: 'internal', slug: 'cost-per-application-benchmarks-2026', label: 'Next: 2026 CPA benchmarks by vertical and platform' },
    ],
  },

  'small-budget-recruitment-plays': {
    title: 'Six recruitment plays under €500/month that actually work',
    slug: 'small-budget-recruitment-plays',
    excerpt: 'Most agencies will tell you that €500/month is unrunnable. It\'s not — but only if you stop pretending you can do what the €5k budgets do, and do something else instead.',
    date: '2026-01-11',
    author: 'HireAds Team',
    readingMinutes: 6,
    tags: ['budgets', 'small-business', 'strategy'],
    related: ['cost-per-application-benchmarks-2026', 'tiktok-hiring-under-25', 'lead-ads-vs-career-site'],
    body: [
      { type: 'p', text: 'Enterprise playbooks fail at €500/month because they assume you can afford a 10-day learning phase on Meta, 3 creative variants per campaign, and a separate remarketing pool. You can\'t. Different rules apply.' },
      { type: 'h2', text: 'The six plays' },
      { type: 'ol', items: [
        'Single-platform focus. Pick the one platform that matches your role demographic, put 100% of budget there. Saves learning-phase waste.',
        'One creative, one variant of copy. A/B testing below €30/day is noise. Pick the one you think is best, commit, iterate weekly.',
        'Lead Ads only. Career-site funnel loses 70% — you can\'t afford that.',
        'Micro-geo. Instead of "Poland" target a 25km radius around your office. Fewer impressions, higher relevance, lower CPM.',
        'Spark Ads / organic boost. Use your own employee\'s video, boost with €10/day. Free content, native feel.',
        'Refresh on a 14-day cadence. Creative fatigue hits harder with small budgets because frequency builds up fast in narrow targeting.',
      ] },
      { type: 'stat', value: '€3.40', label: 'median CPA achieved by our sub-€500/mo accounts running this playbook', source: 'HireAds 2025 SMB cohort, n=62' },
      { type: 'internal', to: '/product/campaigns', label: 'Launch your first campaign from €23 (100 PLN) minimum spend' },
      { type: 'internal', slug: 'lead-ads-vs-career-site', label: 'Next: Why Lead Ads beat career sites on small budgets' },
    ],
  },
}

export const BLOG_POST_SLUGS = Object.keys(BLOG_POSTS)
