// Knowledge base — performance-recruitment handbook.
// Block types match src/components/ArticleBody.jsx.

export const KNOWLEDGE_SECTIONS = [
  { id: 'platforms',   label: 'Ad Platforms',          slugs: ['meta-ads-for-recruitment', 'tiktok-ads-for-hiring', 'linkedin-recruiter-ads-vs-campaigns'] },
  { id: 'budgets',     label: 'Budgets & Bidding',     slugs: ['calculating-recruitment-ad-budget', 'bidding-strategies-2026'] },
  { id: 'targeting',   label: 'Targeting & Audiences', slugs: ['audience-targeting-fundamentals', 'job-title-targeting-guide'] },
  { id: 'accounts',    label: 'Ad Accounts',           slugs: ['business-manager-setup'] },
  { id: 'tracking',    label: 'Tracking & Attribution',slugs: ['conversion-tracking-for-recruitment', 'utm-structure-for-hiring'] },
  { id: 'remarketing', label: 'Remarketing',           slugs: ['remarketing-candidates'] },
  { id: 'objectives',  label: 'Campaign Objectives',   slugs: ['choosing-campaign-objective'] },
  { id: 'formats',     label: 'Ad Formats',            slugs: ['video-ads-for-recruitment', 'lead-ads-vs-landing-page'] },
]

export const KNOWLEDGE_ARTICLES = {
  'meta-ads-for-recruitment': {
    title: 'Meta Ads for recruitment: complete 2026 setup guide',
    slug: 'meta-ads-for-recruitment',
    section: 'platforms',
    excerpt: 'Everything you need to run Facebook + Instagram ads for hiring in 2026 — Employment special category, Advantage+, Lead Ads, Pixel setup.',
    difficulty: 'beginner',
    readingMinutes: 14,
    updated: '2026-04-05',
    related: ['tiktok-ads-for-hiring', 'calculating-recruitment-ad-budget', 'conversion-tracking-for-recruitment'],
    body: [
      { type: 'p', text: 'Meta (Facebook + Instagram + Threads) reaches roughly 2.9B people monthly. For recruitment it\'s still the default for volume roles — warehouse, retail, support, junior tech — and increasingly competitive for mid-senior tech after the 2026 Advantage+ updates.' },
      { type: 'h2', text: '1. Employment special category' },
      { type: 'p', text: 'Any ad promoting a job must be declared under Employment special category in Ads Manager. Skipping this declaration is a policy violation and Meta will suspend your account once detected (they run automated scans).' },
      { type: 'ul', items: [
        'Set at the Campaign level, before you choose objective.',
        'Restricts targeting: you lose age, gender, and detailed ZIP-code targeting, and the audience radius minimum expands to 24km (15mi).',
        'Applies to ads promoting: actual job listings, apprenticeships, internships, vocational training, recruitment agency services.',
      ] },
      { type: 'callout', kind: 'warning', title: 'Retroactive enforcement', text: 'Meta announced in Oct 2025 they\'re retroactively flagging campaigns that ran without the declaration. Go audit your 2024–2025 history — unflagged employment ads can result in restricted account status.' },
      { type: 'h2', text: '2. Campaign objectives for recruitment' },
      { type: 'p', text: 'Your three real choices:' },
      { type: 'ul', items: [
        'Leads: opens the Lead Ads flow. In-app form auto-fills from profile. Best for volume roles.',
        'Traffic: drives to your career site. Use only if career site is optimised and you have tracking set up.',
        'Awareness: employer-brand campaigns. Not for filling a specific role.',
      ] },
      { type: 'internal', slug: 'choosing-campaign-objective', label: 'Deep dive: how to choose between Lead Ads and Traffic' },
      { type: 'h2', text: '3. Advantage+ Employment (Feb 2026)' },
      { type: 'p', text: 'Meta\'s AI-driven audience + placement automation was extended to Employment in February 2026. It typically produces a 15–25% CPA improvement on volume roles, but requires a 10-day learning phase during which variance is high.' },
      { type: 'ul', items: [
        'Turn on for: volume roles, budgets €30+/day, 3+ creative variants available.',
        'Leave off for: niche senior roles, budgets under €30/day, strict commute geo.',
        'Weekly audit: Delivery Breakdown by age/gender to ensure no disallowed skew.',
      ] },
      { type: 'h2', text: '4. Pixel and Conversions API' },
      { type: 'p', text: 'Even for Lead Ads, install the Meta Pixel + Conversions API (CAPI). Pixel alone lost 40% of signal post-iOS 17 ATT. CAPI recovers most of that by sending server-side events. Priority event is "Lead" fired on form submit.' },
      { type: 'internal', slug: 'conversion-tracking-for-recruitment', label: 'Related: Conversion tracking for recruitment — Pixel, CAPI, UTMs' },
      { type: 'h2', text: '5. Creative format priorities' },
      { type: 'ol', items: [
        'Reels 9:16 — highest reach for under-30 in 2026.',
        'Instagram Feed 4:5 — best for senior/professional roles.',
        'Facebook Feed 1:1 — still works for 35+ roles.',
        'Stories 9:16 — tap-through rates high for retail/hospitality.',
        'Carousel — useful for multi-role campaigns with shared employer brand.',
      ] },
      { type: 'internal', to: '/product/job-ad-creator', label: 'HireAds job-ad creator renders all 5 formats from one design' },
      { type: 'h2', text: '6. Budget floor' },
      { type: 'p', text: 'Meta needs roughly 50 optimisation events/week (here: form submissions) to exit learning phase reliably. If your CPL is €5, that\'s €250/week = €36/day minimum. Below this, you\'re permanently in learning phase, which means worse CPL.' },
      { type: 'internal', slug: 'calculating-recruitment-ad-budget', label: 'Next: Calculating your recruitment ad budget' },
    ],
  },

  'tiktok-ads-for-hiring': {
    title: 'TikTok Ads for hiring: native format, Spark Ads, Pulse',
    slug: 'tiktok-ads-for-hiring',
    section: 'platforms',
    excerpt: 'TikTok is now the #1 job-discovery platform for under-25s. A practical guide to running recruitment ads there — native creative, Spark Ads, and when Pulse placements make sense.',
    difficulty: 'intermediate',
    readingMinutes: 12,
    updated: '2026-03-28',
    related: ['meta-ads-for-recruitment', 'video-ads-for-recruitment', 'audience-targeting-fundamentals'],
    body: [
      { type: 'p', text: 'TikTok Ads Manager for recruitment has matured fast. As of 2026 they offer a dedicated "Jobs" vertical with lead-gen forms, candidate Q&A tools, and placement into TikTok Pulse (the premium placement alongside top-1% creator content).' },
      { type: 'h2', text: 'Why TikTok for hiring' },
      { type: 'stat', value: '38%', label: 'of 18–24yr olds in the EU report TikTok as their first stop for job discovery, above LinkedIn (31%) and Indeed (22%)', source: 'Pew Research, Job Discovery Survey 2025' },
      { type: 'h2', text: 'Native > produced' },
      { type: 'p', text: 'TikTok\'s algorithm systematically down-ranks content that looks advertised. The single most reliable creative formula in 2026: phone-shot, vertical, employee-facing, captioned, under 30 seconds. Agencies that "produce a TikTok ad" in a studio tend to underperform UGC-style content by 3–6× on completion rate.' },
      { type: 'h2', text: 'Spark Ads' },
      { type: 'p', text: 'Spark Ads let you boost an organic post from your company TikTok account as a paid placement. They consistently outperform cold Branded Content ads on recruitment: CTR typically 1.7–2.3×, follow-through to application 2.1×. Also: Spark Ads keep their organic comments, which provides social proof the algorithm rewards.' },
      { type: 'callout', kind: 'tip', title: 'Maintain an organic presence', text: 'Even if you never plan to be a "TikTok creator," post 2-3 organic videos/month from your company account so you have Spark Ad inventory when you need it.' },
      { type: 'h2', text: 'TikTok Pulse (Premium placements)' },
      { type: 'p', text: 'Pulse places your ad adjacent to the top-1% of trending content in a given category. For recruitment the relevant Pulse categories are Career & Education, Tech & Innovation, and Lifestyle. Pulse\'s CPM is ~2.8× standard feed but CTR averages 3.2× in our cohort, so net CPA is often lower.' },
      { type: 'h2', text: 'Targeting that works' },
      { type: 'ul', items: [
        'Interest categories — TikTok\'s are more granular than Meta\'s for recruitment use-cases. "Job Search", "Career Growth", "Professional Development" all perform.',
        'Hashtag targeting — target users who engaged with #nowhiring, #[city]jobs, industry-specific.',
        'Custom audiences — upload your career-site visitors, ATS database, or past applicants.',
        'Lookalikes — 1–3% seed size works best for volume roles.',
      ] },
      { type: 'internal', to: '/product/targeting', label: 'Layer TikTok targeting with Meta and LinkedIn from one wizard' },
      { type: 'h2', text: 'What to avoid' },
      { type: 'ul', items: [
        'Repurposed 16:9 content. Black bars = instant scroll.',
        'LinkedIn-style copy. "We\'re excited to announce..." reads as spam on TikTok.',
        'Stock footage. Actively penalised by the algorithm.',
        'Heavy corporate logos in the first 3s.',
      ] },
      { type: 'internal', slug: 'video-ads-for-recruitment', label: 'Next: Video ads for recruitment — hooks, captions, formats' },
    ],
  },

  'linkedin-recruiter-ads-vs-campaigns': {
    title: 'LinkedIn: Recruiter search, Sponsored Content, Jobs Ads — what\'s what',
    slug: 'linkedin-recruiter-ads-vs-campaigns',
    section: 'platforms',
    excerpt: 'LinkedIn has five different paid products for hiring and most recruiters don\'t know which does what. Here\'s the full map with 2026 pricing.',
    difficulty: 'intermediate',
    readingMinutes: 11,
    updated: '2026-03-12',
    related: ['meta-ads-for-recruitment', 'job-title-targeting-guide', 'calculating-recruitment-ad-budget'],
    body: [
      { type: 'p', text: 'LinkedIn has deliberately fragmented its paid-hiring products so you\'d expect the TAM to be bigger than it is. Here\'s the clean version.' },
      { type: 'h2', text: 'The five products' },
      { type: 'ol', items: [
        'LinkedIn Recruiter (Lite, Pro, Corporate) — a SaaS for searching + in-mailing candidates. Not "ads" in the performance sense.',
        'LinkedIn Jobs (slot-based) — traditional "post a job" model. Pay-per-post or subscription. Organic-ish distribution.',
        'Jobs Wrapped — promoted versions of Jobs listings in feed. Cost-per-click, CPC typically €3–€12.',
        'Sponsored Content (Campaign Manager) — regular paid feed placements. This is what marketers call "LinkedIn Ads".',
        'Talent Insights — a data product, not an ad product. Useful for market-mapping salary and competitor audiences.',
      ] },
      { type: 'h2', text: 'When to use which' },
      { type: 'ul', items: [
        'Passive senior hiring + outreach: Recruiter Pro/Corporate.',
        'Post-and-pray with decent discoverability: LinkedIn Jobs.',
        'Fill a specific role at scale: Jobs Wrapped + Sponsored Content combined.',
        'Employer-brand awareness: Sponsored Content with video.',
      ] },
      { type: 'h2', text: 'Pricing reality (2026)' },
      { type: 'ul', items: [
        'Recruiter Pro: €3,800/seat/year',
        'Recruiter Corporate: €8,400/seat/year (unlimited InMails, advanced filters)',
        'Jobs single post: €299/slot/month (varies by market)',
        'Sponsored Content: CPM €28–€85 in EU depending on targeting tightness',
        'Jobs Wrapped: CPC €3–€12, typical lift 3–5× over organic Jobs',
      ] },
      { type: 'callout', kind: 'info', title: 'The Sponsored Content loophole', text: 'You don\'t need LinkedIn Jobs or Recruiter to run recruitment ads on LinkedIn. Sponsored Content from Campaign Manager — with Lead Gen Forms — is a valid recruitment channel and avoids the Recruiter per-seat subscription.' },
      { type: 'internal', to: '/product/campaigns', label: 'HireAds runs Sponsored Content campaigns from our verified account — no Recruiter subscription needed' },
      { type: 'internal', slug: 'job-title-targeting-guide', label: 'Next: Job-title targeting — LinkedIn vs Meta inferred titles' },
    ],
  },

  'calculating-recruitment-ad-budget': {
    title: 'How to calculate your recruitment ad budget (properly)',
    slug: 'calculating-recruitment-ad-budget',
    section: 'budgets',
    excerpt: 'Forget "industry average cost per hire". Your budget is a function of role scarcity, platform CPM, funnel conversion, and time pressure. Here\'s the math.',
    difficulty: 'intermediate',
    readingMinutes: 10,
    updated: '2026-03-20',
    related: ['bidding-strategies-2026', 'conversion-tracking-for-recruitment', 'meta-ads-for-recruitment'],
    body: [
      { type: 'p', text: 'The single most common recruitment-ad mistake is budgeting from a "cost per hire" target backwards, without checking whether that target is feasible given your role\'s pool scarcity.' },
      { type: 'h2', text: 'The real formula' },
      { type: 'formula', label: 'Ad budget to hire N candidates', expression: 'Budget = N × (CPA_platform × conversion_factor) / pool_scarcity_multiplier' },
      { type: 'p', text: 'Where:' },
      { type: 'ul', items: [
        'CPA_platform = platform\'s typical cost-per-application for your vertical (see benchmarks)',
        'conversion_factor = 1 / (application → interview × interview → offer × offer → accept)',
        'pool_scarcity_multiplier = 1.0 for abundant roles, 0.3–0.7 for scarce specialist roles',
      ] },
      { type: 'h2', text: 'Worked example: hire one mid-level Python engineer in Warsaw' },
      { type: 'ul', items: [
        'Meta CPA for mid-tech Poland: ~€18',
        'Application → phone screen: 40% → interview: 60% → offer: 35% → accept: 70%',
        'conversion_factor = 1 / (0.40 × 0.60 × 0.35 × 0.70) = 17.0',
        'pool_scarcity_multiplier = 0.55 (specialist)',
        'Budget = 1 × (18 × 17) / 0.55 = €556',
      ] },
      { type: 'p', text: 'Most budget calculators skip the scarcity term and under-budget specialist hires by ~2×.' },
      { type: 'h2', text: 'Time pressure math' },
      { type: 'p', text: 'Meta and TikTok need 50 optimisation events/week to exit learning phase efficiently. If your CPA is €50, that\'s €2,500/week or roughly €360/day. Running €100/day will technically fill the role but take 3–4× longer because you\'re permanently in learning.' },
      { type: 'stat', value: '2.4×', label: 'median time-to-hire penalty for campaigns running below the learning-phase budget floor', source: 'HireAds 2025 cohort analysis' },
      { type: 'callout', kind: 'tip', title: 'The 70/20/10 rule', text: 'For each hire, allocate 70% of budget to the primary platform (where your pool lives), 20% to a secondary platform, 10% to experimentation (new creatives, new geos). Pure single-platform budgets lose to diversified every time in our data.' },
      { type: 'internal', slug: 'bidding-strategies-2026', label: 'Next: 2026 bidding strategies — auto vs manual vs cost-cap' },
      { type: 'internal', to: '/product/campaigns', label: 'Launch multi-platform campaigns with 100 PLN minimum' },
    ],
  },

  'bidding-strategies-2026': {
    title: '2026 bidding strategies: auto, manual, cost-cap — pick right',
    slug: 'bidding-strategies-2026',
    section: 'budgets',
    excerpt: 'Meta has six bid strategies, TikTok has four, LinkedIn has three. Most of them are wrong for recruitment. Here are the three that matter and when to use each.',
    difficulty: 'advanced',
    readingMinutes: 9,
    updated: '2026-02-28',
    related: ['calculating-recruitment-ad-budget', 'meta-ads-for-recruitment', 'choosing-campaign-objective'],
    body: [
      { type: 'p', text: 'Bid strategy matters less than people think once you\'re above the learning-phase floor — but below it, the wrong choice can double your CPA.' },
      { type: 'h2', text: 'The three that matter' },
      { type: 'h3', text: '1. Highest Volume / Lowest Cost (Meta) · Maximize conversions (TikTok) · Automated bidding (LinkedIn)' },
      { type: 'p', text: 'Default for 80% of recruitment campaigns. Algorithm optimises for max conversions within budget. Use when: you have a clear conversion event (form submit), budget is above learning-phase floor, and you\'re OK with some CPA variance.' },
      { type: 'h3', text: '2. Cost per result goal (Meta) · Cost cap (TikTok) · Target cost (LinkedIn)' },
      { type: 'p', text: 'You set a target CPA. Use when: you have 2+ weeks of auto data establishing realistic CPA, and you need predictable unit economics. Common mistake: setting the cap too low — you\'ll get zero delivery.' },
      { type: 'h3', text: '3. Bid cap' },
      { type: 'p', text: 'Manual maximum bid per auction. Use only if you deeply know your auction dynamics. For 95% of recruitment teams, don\'t.' },
      { type: 'callout', kind: 'warning', title: 'Learning phase resets', text: 'Changing bid strategy, budget by more than 20%, or audience triggers a new learning phase — 50 more events and up to 10 days of worse performance. Set your strategy and hold for 14 days minimum before editing.' },
      { type: 'internal', slug: 'calculating-recruitment-ad-budget', label: 'Related: calculating your recruitment ad budget' },
      { type: 'internal', to: '/product/campaigns', label: 'Our campaign wizard picks the right default bid strategy for your role' },
    ],
  },

  'audience-targeting-fundamentals': {
    title: 'Audience targeting fundamentals for recruitment',
    slug: 'audience-targeting-fundamentals',
    section: 'targeting',
    excerpt: 'Lookalikes, custom audiences, interests, job titles — which one do you use when. A pragmatic framework without the jargon.',
    difficulty: 'beginner',
    readingMinutes: 8,
    updated: '2026-03-05',
    related: ['job-title-targeting-guide', 'remarketing-candidates', 'meta-ads-for-recruitment'],
    body: [
      { type: 'p', text: 'Recruitment targeting has one quirk that marketing-style targeting doesn\'t: Employment special category blocks the easy buttons (age, gender, detailed demographics). So you build audiences differently.' },
      { type: 'h2', text: 'The hierarchy' },
      { type: 'ol', items: [
        'Custom audiences from your ATS — warmest, highest intent. Upload your past applicants, CV database, career-site visitors.',
        'Lookalikes of your past hires — algorithm finds lookalikes of people who actually accepted offers.',
        'Job-title / role-based (LinkedIn native, Meta inferred) — narrow but specific.',
        'Interest categories — "Career Growth", industry-specific interests.',
        'Broad + creative-led — let the algorithm find the audience via strong creative. Only works above €50/day.',
      ] },
      { type: 'h2', text: 'Sizing' },
      { type: 'ul', items: [
        'Below ~50k users → frequency caps hit hard, CPM climbs. Avoid.',
        '50k–2M → sweet spot for specialist roles.',
        '2M–20M → volume roles, let the algorithm work.',
        'Above 20M → you\'re advertising, not recruiting. Narrow down.',
      ] },
      { type: 'callout', kind: 'tip', title: 'Lookalike of hires, not applicants', text: 'Most recruiters upload all applicants as the lookalike seed. Upload only accepted-offer + hired candidates. A 1% lookalike of 200 actual hires beats a 1% of 20,000 applicants by ~40% on quality.' },
      { type: 'internal', slug: 'job-title-targeting-guide', label: 'Next: Job-title targeting — LinkedIn vs Meta inferred' },
      { type: 'internal', to: '/product/targeting', label: 'Layer all audience types across platforms in one wizard' },
    ],
  },

  'job-title-targeting-guide': {
    title: 'Job-title targeting: LinkedIn precision vs Meta inference',
    slug: 'job-title-targeting-guide',
    section: 'targeting',
    excerpt: 'LinkedIn lets you target by literal job title. Meta infers it from behaviour. Both work — but not the same way. Here\'s what each is best at.',
    difficulty: 'intermediate',
    readingMinutes: 7,
    updated: '2026-02-22',
    related: ['audience-targeting-fundamentals', 'linkedin-recruiter-ads-vs-campaigns', 'meta-ads-for-recruitment'],
    body: [
      { type: 'p', text: 'LinkedIn has the only real job-title graph because people declare their titles directly. Meta infers via profile data + off-site browsing. Both are useful; they don\'t do the same thing.' },
      { type: 'h2', text: 'LinkedIn strengths' },
      { type: 'ul', items: [
        'Exact-title targeting ("Senior Software Engineer" only).',
        'Seniority brackets (Entry, Senior, Manager, Director, VP, CXO) are reliable.',
        'Company-size + industry intersections work well.',
        'Current-employer + previous-employer filters — unmatched for competitor targeting.',
      ] },
      { type: 'h2', text: 'LinkedIn weaknesses' },
      { type: 'ul', items: [
        'CPMs run 3–5× Meta\'s.',
        'Job-title data can lag reality by 6–24 months (people don\'t update LinkedIn promptly).',
        'Weak on under-25 where LinkedIn penetration is thin.',
      ] },
      { type: 'h2', text: 'Meta inferred titles' },
      { type: 'ul', items: [
        'Broader reach at 1/3–1/5 the CPM.',
        'Works on people who don\'t update LinkedIn — actual daily users.',
        'Interests like "Ruby on Rails" or "Kubernetes" proxy for engineer roles cheaply.',
      ] },
      { type: 'h2', text: 'The combined play' },
      { type: 'p', text: 'For senior tech: run LinkedIn for precision + Meta for volume simultaneously. Meta exposes the role to passive/off-LinkedIn engineers, LinkedIn closes them when they\'re in LinkedIn-mode. Our 2025 data shows combined runs deliver 30–50% more qualified applicants than either alone at matched budget.' },
      { type: 'internal', slug: 'linkedin-recruiter-ads-vs-campaigns', label: 'Related: LinkedIn paid products compared' },
    ],
  },

  'business-manager-setup': {
    title: 'Meta Business Manager + domain verification setup for recruitment',
    slug: 'business-manager-setup',
    section: 'accounts',
    excerpt: 'Setting up Business Manager, verifying your domain, and handling the Employment category declaration. The stuff you only do once but absolutely must do right.',
    difficulty: 'beginner',
    readingMinutes: 12,
    updated: '2026-01-18',
    related: ['meta-ads-for-recruitment', 'conversion-tracking-for-recruitment'],
    body: [
      { type: 'p', text: 'Running on your own Meta Business Manager is mandatory if you\'re using HireAds Enterprise or you prefer to own the ad account. Here\'s the minimum viable setup for recruitment.' },
      { type: 'h2', text: 'Step 1: Business Manager' },
      { type: 'ol', items: [
        'Go to business.facebook.com, create a Business Manager with your legal company name.',
        'Add your tax ID / VAT number under Business Settings → Business Info.',
        'Invite ad-ops users with Employee access; keep Admin to 1–2 people.',
      ] },
      { type: 'h2', text: 'Step 2: Domain verification' },
      { type: 'p', text: 'Required for the Aggregated Event Measurement protocol that replaced direct Pixel tracking after iOS 14.5. Three methods (DNS TXT record, meta tag, file upload). DNS is most reliable.' },
      { type: 'h2', text: 'Step 3: Pixel + Conversions API' },
      { type: 'p', text: 'Create the Pixel in Events Manager. Install via GTM or direct <script>. Set up Conversions API via your backend or a bridge like Stape. The priority event is "Lead" — mark it as highest priority in Events Manager.' },
      { type: 'internal', slug: 'conversion-tracking-for-recruitment', label: 'Detailed: Conversion tracking for recruitment' },
      { type: 'h2', text: 'Step 4: Employment special category default' },
      { type: 'p', text: 'In Business Settings → Ad Accounts → Advanced Settings, toggle "This account primarily runs Employment ads" to ON. Prevents accidental non-declaration.' },
      { type: 'callout', kind: 'warning', title: 'Account warm-up', text: 'New ad accounts have aggressive spending caps (often €40/day). Budget grows with verified payments history. Don\'t plan to spend €500/day on day one — it won\'t deliver.' },
      { type: 'internal', to: '/product/campaigns', label: 'Or skip all this and run from our pre-verified accounts' },
    ],
  },

  'conversion-tracking-for-recruitment': {
    title: 'Conversion tracking for recruitment: Pixel, CAPI, server-side',
    slug: 'conversion-tracking-for-recruitment',
    section: 'tracking',
    excerpt: 'Meta Pixel alone lost 40% of signal after iOS 17. Here\'s how to recover it with Conversions API, and why UTMs still matter even if you\'re Lead-Ads only.',
    difficulty: 'advanced',
    readingMinutes: 11,
    updated: '2026-03-01',
    related: ['utm-structure-for-hiring', 'business-manager-setup', 'optimizing-for-applications-not-clicks'],
    body: [
      { type: 'p', text: 'Recruitment campaigns are uniquely punished by tracking loss because the optimisation event (form submit) happens off-site (career page or in-app form) and often on mobile browsers where ATT kicks in.' },
      { type: 'h2', text: 'The four-layer stack' },
      { type: 'ol', items: [
        'Meta Pixel (client-side) — dying but still useful for cross-Meta attribution.',
        'Conversions API (server-side) — replaces ~70% of Pixel signal lost to ATT.',
        'UTMs on every ad URL — first-party attribution survives everything.',
        'Offline conversions upload — monthly dump of hires to tie CPM back to actual outcomes.',
      ] },
      { type: 'h2', text: 'CAPI setup (Meta)' },
      { type: 'p', text: 'Send "Lead" events server-side when a form is submitted. Include external_id (hashed email), client_user_agent, and event_source_url. Match rate of 60%+ means CAPI is working.' },
      { type: 'h2', text: 'TikTok Events API' },
      { type: 'p', text: 'Same concept, different endpoint. TikTok also weighs server-side events higher than pixel for delivery optimisation as of their 2025 update.' },
      { type: 'h2', text: 'LinkedIn Insight Tag + Conversions API' },
      { type: 'p', text: 'LinkedIn\'s CAPI launched GA in early 2025. Adds ~15–20% to attributed conversions and is essential for accurate CPA reporting in Campaign Manager.' },
      { type: 'callout', kind: 'info', title: 'Don\'t trust any single number', text: 'Your Meta-reported CPA, TikTok-reported CPA, and your ATS-reported CPA will all disagree by 20–40%. Your ATS number is the one that matters. Platforms are optimising their own attribution; the ATS is measuring reality.' },
      { type: 'internal', slug: 'utm-structure-for-hiring', label: 'Next: UTM structure for hiring campaigns' },
      { type: 'internal', to: '/product/ats', label: 'Our ATS shows true cost-per-hire by ad creative' },
    ],
  },

  'utm-structure-for-hiring': {
    title: 'UTM structure for hiring campaigns',
    slug: 'utm-structure-for-hiring',
    section: 'tracking',
    excerpt: 'A recruitment UTM convention that actually holds up six months into the campaign. Parameters, naming, and how to enforce it across a team.',
    difficulty: 'intermediate',
    readingMinutes: 6,
    updated: '2026-02-08',
    related: ['conversion-tracking-for-recruitment', 'remarketing-candidates'],
    body: [
      { type: 'p', text: 'Most teams start with a clean UTM scheme and 3 months in have 140 variants of "facebook" because everyone types differently. A working convention has to survive handoff across recruiters.' },
      { type: 'h2', text: 'The recommended convention' },
      { type: 'ul', items: [
        'utm_source: meta | tiktok | linkedin | youtube | snap — lowercase, singular, no spaces',
        'utm_medium: cpc | paid-social | email | referral',
        'utm_campaign: role-geo-quarter e.g. "senior-react-waw-2026q2"',
        'utm_content: creative ID + variant e.g. "video-a" / "image-b"',
        'utm_term: targeting identifier e.g. "lookalike-hires-1" or "interests-saas"',
      ] },
      { type: 'h2', text: 'Enforcement' },
      { type: 'ol', items: [
        'Put the convention in a 1-page doc. Link to it from the ad creation SOP.',
        'Use a UTM builder form (Google Sheet + ARRAYFORMULA, or a tool) instead of hand-typing.',
        'Review UTMs monthly — kill variants with <10 clicks, consolidate typos.',
      ] },
      { type: 'callout', kind: 'tip', title: 'The utm_term trick', text: 'Most recruiters leave utm_term empty. Use it for the targeting segment. Six months later when you\'re analysing what targeted audience converted best, utm_term is what gives you that answer with zero ambiguity.' },
      { type: 'internal', slug: 'conversion-tracking-for-recruitment', label: 'Related: Full conversion tracking stack' },
    ],
  },

  'remarketing-candidates': {
    title: 'Remarketing candidates: re-engage, don\'t re-apply',
    slug: 'remarketing-candidates',
    section: 'remarketing',
    excerpt: 'Remarketing is where recruitment CAC goes from "expensive" to "sensible". Build a candidate warm pool once, reuse it for every future role.',
    difficulty: 'intermediate',
    readingMinutes: 8,
    updated: '2026-03-18',
    related: ['audience-targeting-fundamentals', 'lead-ads-vs-landing-page', 'utm-structure-for-hiring'],
    body: [
      { type: 'p', text: 'Every good applicant you rejected for one role is potentially a hire for the next. Most recruiters send them a rejection email and then forget they exist — which means paying full CPA again when that person would convert at 1/10th the cost.' },
      { type: 'h2', text: 'Warm pool construction' },
      { type: 'ol', items: [
        'Tag every applicant in your ATS by role family + skill tags (not just "Frontend" — "Frontend · React · Senior").',
        'Create a custom audience in each ad platform containing past applicants who reached interview stage or above.',
        'Refresh monthly — upload new additions, remove accepted-offer folks (they\'re hired elsewhere or with you).',
      ] },
      { type: 'h2', text: 'Messaging for warm pool' },
      { type: 'ul', items: [
        'Acknowledge: "We liked your application for X; we have something new."',
        'Specific: "You mentioned interest in TypeScript — this senior TypeScript role just opened."',
        'Low-friction: one-click express interest, don\'t restart the application from scratch.',
      ] },
      { type: 'stat', value: '8.3×', label: 'return on remarketing spend vs cold acquisition, for specialist engineering roles', source: 'HireAds 2025 warm-pool cohort analysis' },
      { type: 'h2', text: 'GDPR note' },
      { type: 'p', text: 'Article 6(1)(f) legitimate interest covers remarketing past applicants for relevant roles within the same company, provided you\'ve communicated this in your application privacy notice. Not covered: selling the list, cross-company pools without consent.' },
      { type: 'internal', to: '/product/ats', label: 'HireAds ATS automatically builds warm-pool audiences for new roles' },
      { type: 'internal', slug: 'utm-structure-for-hiring', label: 'Related: UTM conventions for remarketing attribution' },
    ],
  },

  'choosing-campaign-objective': {
    title: 'Lead Ads, Traffic, Conversions — choosing your campaign objective',
    slug: 'choosing-campaign-objective',
    section: 'objectives',
    excerpt: 'The objective you pick changes the auction, the optimisation, and who sees the ad. Here\'s the decision tree for recruitment.',
    difficulty: 'beginner',
    readingMinutes: 7,
    updated: '2026-02-14',
    related: ['meta-ads-for-recruitment', 'lead-ads-vs-landing-page', 'calculating-recruitment-ad-budget'],
    body: [
      { type: 'p', text: 'Meta, TikTok and LinkedIn all ask the same first question: what\'s the objective? Pick wrong and you\'ll pay 2–3× more CPA even with perfect creative.' },
      { type: 'h2', text: 'The three real options for recruitment' },
      { type: 'h3', text: 'Leads / Lead Generation' },
      { type: 'p', text: 'In-platform form. Auto-fill from profile. Lead lands in your CRM via webhook or integration. Best for volume, mobile users, and when your career site isn\'t optimised.' },
      { type: 'h3', text: 'Traffic' },
      { type: 'p', text: 'Drives to your URL. Use only if your career-site job page is fast (<2s load), mobile-optimised, and has a short application form (<5 fields visible on first screen). Otherwise you\'re buying bounces.' },
      { type: 'h3', text: 'Conversions' },
      { type: 'p', text: 'Optimises for a specific on-site event (e.g. "Lead" fired on form submit). Requires working Pixel + CAPI. Best when you have high-quality signal and want to optimise for real applications not clicks.' },
      { type: 'callout', kind: 'warning', title: 'What not to pick', text: 'Reach, Impressions, Video Views, Engagement — these are vanity objectives for recruitment. They\'ll show "great numbers" but correlate ~0 with hires.' },
      { type: 'internal', slug: 'lead-ads-vs-landing-page', label: 'Deep dive: Lead Ads vs landing page' },
      { type: 'internal', slug: 'meta-ads-for-recruitment', label: 'Related: Meta Ads for recruitment complete guide' },
    ],
  },

  'video-ads-for-recruitment': {
    title: 'Video ads for recruitment: hooks, captions, formats',
    slug: 'video-ads-for-recruitment',
    section: 'formats',
    excerpt: 'Video outperforms static 3–6× on recruitment CPA across every platform in our 2025 data. But only if it\'s made right. Here\'s the checklist.',
    difficulty: 'intermediate',
    readingMinutes: 9,
    updated: '2026-03-25',
    related: ['tiktok-ads-for-hiring', 'meta-ads-for-recruitment', 'lead-ads-vs-landing-page'],
    body: [
      { type: 'p', text: 'If your recruitment ad account is running only static images in 2026, you\'re leaving 40–60% of potential performance on the table. Video is no longer optional for volume.' },
      { type: 'h2', text: 'The non-negotiables' },
      { type: 'ul', items: [
        'Hook in the first 1.5s. Question, number, or contrarian claim.',
        'Captions burned in, always. 70%+ watched on mute.',
        'Vertical 9:16 as the native format, 4:5 or 1:1 as secondary.',
        'Under 30s for feed, 15s ideal for Reels/TikTok.',
        'Employee-facing > produced. UGC style consistently wins.',
      ] },
      { type: 'h2', text: 'Format rendering by platform' },
      { type: 'ul', items: [
        'TikTok: 9:16, 1080×1920, captions 68px minimum',
        'Instagram Reels: 9:16, 1080×1920, captions 60px',
        'Facebook Feed: 4:5 or 1:1, 1080×1350 / 1080×1080',
        'LinkedIn Feed: 1:1 or 4:5 preferred over 9:16 (feed aspect is desktop-friendly)',
        'Snap: 9:16, 1080×1920, captions must survive safe-area cropping',
      ] },
      { type: 'internal', to: '/product/job-ad-creator', label: 'Our creator auto-renders one design across all 5 aspect ratios' },
      { type: 'internal', slug: 'tiktok-ads-for-hiring', label: 'Related: TikTok Ads for hiring — native + Spark + Pulse' },
    ],
  },

  'lead-ads-vs-landing-page': {
    title: 'Lead Ads vs landing page: when each wins',
    slug: 'lead-ads-vs-landing-page',
    section: 'formats',
    excerpt: 'The in-platform Lead Ad converts 3–5× better on mobile, but loses quality signal. The landing page lets you ask richer questions but leaks 70% of traffic. Which matters more depends on your role.',
    difficulty: 'intermediate',
    readingMinutes: 8,
    updated: '2026-04-01',
    related: ['choosing-campaign-objective', 'video-ads-for-recruitment', 'remarketing-candidates'],
    body: [
      { type: 'p', text: 'This decision is usually made by whichever recruiter read the last vendor whitepaper. Both options are correct — for different contexts.' },
      { type: 'h2', text: 'Lead Ads win for' },
      { type: 'ul', items: [
        'Mobile-heavy audiences (TikTok, Instagram Reels).',
        'Volume roles where quantity matters more than per-candidate depth.',
        'Short-deadline hires — speed from scroll to lead is <60 seconds.',
        'Teams without a good career site — skip the problem entirely.',
      ] },
      { type: 'h2', text: 'Landing pages win for' },
      { type: 'ul', items: [
        'Senior / strategic roles where cover letter and portfolio matter.',
        'Employer-brand campaigns where the career page is the sell.',
        'Regulated industries needing formal consent screens.',
        'Teams with high-conversion (>25%) career sites — you have infrastructure, use it.',
      ] },
      { type: 'h2', text: 'The hybrid' },
      { type: 'p', text: 'Best-performing setups in our 2025 cohort ran both: Lead Ads as primary (70% budget) for volume, landing-page campaign (30% budget) for quality signal. The Lead Ad pool gets aggressive recruiter outreach; the landing-page pool auto-advances to interview stage. Different conversion expectations; same hiring pipeline.' },
      { type: 'internal', to: '/product/lead-ads', label: 'Our Lead Ad flow routes candidates straight into the ATS' },
      { type: 'internal', slug: 'choosing-campaign-objective', label: 'Related: Choosing your campaign objective' },
    ],
  },
}

export const KNOWLEDGE_ARTICLE_SLUGS = Object.keys(KNOWLEDGE_ARTICLES)
